PolymerElements/paper-styles

bower.json

Remove dangling commas in bower.json so it validates.

Remove dangling commas

---

README.md
bower.json
demo.css
x-color.html
x-paper-styles.html
x-theme.html
x-typography.html

@nevir PTAL cc @cdata 
I only added the few styles used by PolymerElements/paper-item but the idea is to add to it as needed. I'm not sure how to solve the duplication issue, since there's not a good way to include regular styles elsewhere.

add a couple styles using custom variables

---

x-typography.html

@morethanreal 
Also see it in use via https://github.com/PolymerElements/iron-doc-viewer/pull/2

Fill in the rest of x-typography

---

classes/layout.html
classes/shadow-layout.html
layout.html
paper-styles-classes.html
paper-styles.html

add layout style definitions

---

paper-styles.html

include layout classes

---

bower.json
color.html
default-theme.html
demo/index.html
paper-styles-classes.html
paper-styles.html
shadow.html
typography.html

- `mixin` -> `@apply`
- `x-style` -> `custom-style`
- bower and license updates

Update for 0.9-rc.1

---

bower.json
demo-pages.html
demo/index.html
shadow.html

I've had to add the styles to the `html` and not the `css` to get the custom style to work. And added them to the demo.
/cc @morethanreal @cdata

add demo styles

---

demo-pages.html

When it isn't tonight, this should be replaced with a nice css class.
/cc @cdata

wrap demo pages nicely

---

color.html

Fixed opacities being expressed as precentage

---

demo-pages.html

cc @cdata @morethanreal @notwaldorf

Include typography in demo-pages.html

---

typography.html

`--paper-font-common-base`
` --paper-font-common-code`
`--paper-font-common-expensive-kerning`
`--paper-font-common-nowrap`
cc @cdata @notwaldorf

Expose granular mixins

---

shadow.html

For https://github.com/PolymerElements/paper-styles/issues/14 PTAL @notwaldorf

add --shadow-none variable to reset shadows

---

classes/shadow.html

For https://github.com/PolymerElements/paper-styles/issues/11 PTAL @notwaldorf

update classes/shadow.html to match shadow.html

---

bower.json
typography.html

Depends on https://github.com/PolymerElements/font-roboto/pull/4

Import font-roboto rather than load the font file directly.

---

classes/typography.html

fixes Roboto loading path (which breaks vulcanize)

fix Roboto path

---

demo/index.html

A small typo in the demo page :)

Demo was applying body1 theme to the body2 class

---

classes/shadow-layout.html

Fix typo in CSS: botttom -> bottom

---

demo/index.html
paper-styles.html

Added a note about using the individual imports, and changed the demo to match that.

stop bringing in the paper-styles kitchen sink

---

classes/typography.html

This updates the class to match what's in `paper-styles/typography.html`.

Fix paper-font-code1 font-weight

---

default-theme.html

based on https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors and discussed in https://github.com/PolymerElements/paper-styles/issues/94

added --error-color

---

element-styles/paper-item.html
element-styles/paper-material.html

This is basically https://github.com/PolymerElements/paper-styles/pull/132, but it needs to be cherry picked to master as well so that the hybrid 1.0 version can pick it up

add mixins for the shared styles

---

element-styles/paper-item-styles.html
element-styles/paper-material-styles.html

Can't duplicate the `dom-module` id names :sob:

fixes #130

---

test/index.html

WCT fails if it can't find any tests to run.

Add an empty test suite to satisfy WCT.
