PolymerElements/paper-styles

bower.json
On case-sensitive filesystems the capitalization was causing Polymer to double-install in the bower_components directory.
=> Lower case polymer dependency

demo/index.html, paper-styles.html, shadow.html
@shyndman @cdata @notwaldorf @nevir PTAL
=> update shadow values. now with ∞ more umbra

demo.css, shadow.html
**Material design spec audit https://github.com/PolymerElements/paper-button/issues/12**
* Use `Roboto', 'Noto', sans-serif` instead of `RobotoDraft` in the demos.
* Make the shadows a bit stronger as it's required by the spec. This change should also solve https://github.com/PolymerElements/paper-button/issues/10
cc @cdata @notwaldorf
=> RobotoDraft -> Roboto and shadows

demo-pages.html, demo/index.html
I've named the sections so that they don't have to be css hacked in the future, and added a thin centered vertical column.
/cc @cdata @blasten
=> cleanup demo styles

demo-pages.html
Fixed sizes are sad on mobile, and they make the demo too wide. I haven't found code that sets a different width for this, so this shouldn't break any existing demos. I really shouldn't be allowed to write CSS :(
/cc @morethanreal @cdata @blasten 
Before:
After:
=> fix centered vertical-section's size on mobile

color.html
The paper-brown colors 50-200 do not match the color palette here: http://www.google.com/design/spec/style/color.html#color-color-palette
Fixed colors to match.
=> Fix brown colors in color.html

color.html
Deep orange colors were messed up. 
Particularly:
paper-deep-orange-50 was paper-deep-orange-500,
paper-deep-orange-100 was paper-deep-orange-50,
and paper-deep-orange-200 was paper-deep-orange-100.
This PR fixes the issue.
=> Fix deep orange

bower.json, demo/index.html, index.html, paper-styles.html, typography.html
Gave a much needed love to this element:
- fixes #54: the demo was lollerific, and before custom styles were a Real Thing™
- fixes #51: removed `optimizeLegibility`, which is bad news bears. it's still available as a mixin
- fixes #48: there was no way to get to the demo or docs in the elements catalog. Now there's even a minor docs blurb!
=> holy moly cleanup

color.html
The Material Design specifications says that icons with dark text should use an opacity of 38% (https://www.google.com/design/spec/style/color.html#color-ui-color-application).
Paper-styles indicates that icons should use the secondary opacity (54%) (https://github.com/PolymerElements/paper-styles/blob/master/color.html#L322)
Additionally, the spec says that the hint/disabled opacity should be 38% whereas paper-styles implements 26%.
Fixes#67
=> Opacity for dark text mismatches with Material Design specification

demo-pages.html, typography.html
Nested applies actually work, so let's do that instead. Also, this will allow us to be able to change the font magically for all paper elements, by overriding the right mixin:
```css
<style is="custom-style">
:root {
--paper-font-common-base: {
font-family: serif !important;
};
};
</style>
```
=> use nested @applies instead of copy pasta

default-theme.html
I've added new theme-suffixed variables for the colors in https://www.google.com/design/spec/style/color.html#color-ui-color-application. I've added a "deprecated" section with all the weirdly named vestigial ones, and I've marked what they correspond to in this brave new world.
Fixes https://github.com/PolymerElements/paper-styles/issues/81, https://github.com/PolymerElements/polymer-starter-kit/issues/436
=> clean up default-theme values

default-theme.html
This was one of the other old names leftover from the previous theme, and as someone mentioned in https://github.com/PolymerElements/paper-styles/pull/82#discussion_r47791851, `primary-color` better matches `accent-color` (sans the default)
=> minor name cleanup

default-theme.html
There was some confusion in https://github.com/PolymerElements/paper-styles/issues/75 about the "deprecated values" comment, so I've updated it (and moved sections around for clarity).
=> cleaned up comments again

demo/index.html, shadow.html
This is eventually needed for `<paper-fab>`'s pressed state. See PolymerElements/paper-fab#35
=> Added shadow elevation 12dp

classes/typography.html
<header> is for a "heading" section rather than the heading itself. HTML5 has
a note saying
> A header element is intended to usually contain the section's heading (an h1–h6 element), [---]
indicating this is indeed not meant has a heading. `display2` is used for
`<h1>` in global.html, so use that as an example instead.
Closes #108.
=> Replace <header> with <h1> in classes/typography example.

shadow.html
This PR fixes #112
According to the material design documentation, the shadow elevation rises up to 24 dp, concretely this level is used for _dialog_ and _picker_ components.
=> Added shadow elevation 24dp

classes/shadow-layout.html
shadow-layout.html looks like a clone of iron-shadow-flex-layout.html so I copied the warning from there: https://github.com/PolymerElements/iron-flex-layout/blob/master/classes/iron-shadow-flex-layout.html
=> Add deprecation warning to file using /deep/

element-styles/paper-item.html, element-styles/paper-material.html
This is needed so that hybrid elements that need to use `paper-material` (like `paper-card` for example) can actually run with the 1.0 dependency of `paper-styles`
=> add paper-item and paper-material as standalone styles

element-styles/paper-item.html, element-styles/paper-material.html
so we don't have to use host class names that users might stomp on.
would be used like so: https://github.com/PolymerElements/paper-button/pull/153
=> add mixins for the shared styles 

element-styles/paper-item.html, element-styles/paper-material.html
Ok so @azakus said that `:host` needs to come first because he wrote a regex and has regrets.
=> :host needs to come first because regex

.travis.yml, package-lock.json, package.json
Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.
What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more!
=> Automatic format!

README.md
Some of the links in the README where to .html files that didn't exist. Changed to .js
=> Update README: Changed links to js files
